[package]
name = "save-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
save-common = { path = "../save-common" }
tokio = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }
fail = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
rand = "0.9"

[features]
default = []
failpoints = ["fail"]

[[bench]]
name = "storage"
harness = false
