[package]
name = "save-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
save-common = { path = "../save-common" }
save-storage = { path = "../save-storage" }
save-metadata = { path = "../save-metadata" }
save-proto = { path = "../save-proto" }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["io"] }
futures = "0.3"
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
hex = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
prometheus = { workspace = true }
nix = { workspace = true }
dashmap = { workspace = true }
socket2 = { workspace = true }
rand = { workspace = true }
fail = { workspace = true, optional = true }
tonic = { workspace = true }
prost = { workspace = true }
bytes = "1"
http = "1"
http-body = "1"
http-body-util = { workspace = true }
tower = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
filetime = "0.2"
roxmltree = "0.21.1"

[features]
default = []
failpoints = ["dep:fail", "save-storage/failpoints", "save-metadata/failpoints"]
