[package]
name = "save-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
save-common = { path = "../save-common" }
save-storage = { path = "../save-storage" }
save-metadata = { path = "../save-metadata" }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["io"] }
futures = "0.3"
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sha2 = { workspace = true }
hmac = "0.12"
hex = "0.4"
chrono = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
prometheus = { version = "0.14.0", default-features = false }

[dev-dependencies]
tower = { workspace = true }
http-body-util = { workspace = true }
tempfile = { workspace = true }
filetime = "0.2"
roxmltree = "0.21.1"
