[package]
name = "save-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "save-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
tokio = { workspace = true }
anyhow = { workspace = true }
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
reqwest = "0.12"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
