[package]
name = "save-metadata"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
save-common = { path = "../save-common" }
tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
rocksdb = { workspace = true }
bincode = { workspace = true }
chrono = { workspace = true }
fail = { workspace = true, optional = true }
openraft = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
criterion = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }

[features]
default = []
failpoints = ["fail"]

[[bench]]
name = "metadata"
harness = false
