[package]
name = "save-metadata"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
save-common = { path = "../save-common" }
save-proto = { path = "../save-proto" }
tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
rocksdb = { workspace = true }
bincode = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
fail = { workspace = true, optional = true }
openraft = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
async-trait = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tokio-stream = "0.1"
http = "1.2"
prost = { workspace = true }
http-body = "1.0"
http-body-util = { workspace = true }
bytes = "1.10"
tower = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
criterion = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }

[features]
default = []
failpoints = ["fail"]

[[bench]]
name = "metadata"
harness = false
