[package]
name = "aws-sdk-compat"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []
compat_tests = []

[dependencies]
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
