global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'save-cluster'

rule_files:
  - '/etc/prometheus/alerts.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'save-cluster'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'save-node1:9000'
          - 'save-node2:9000'
          - 'save-node3:9000'
        labels:
          cluster: 'save-cluster'
          env: 'dev'

  - job_name: 'haproxy'
    scrape_interval: 10s
    static_configs:
      - targets: ['save-lb:8404']
        labels:
          service: 'haproxy'
